Spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/movieTicketing
    username : sa
    password :
    driver-class-name : org.h2.Driver

  jpa:
    hibernate:
      ddl-auto : update      # application 실행 시점에 내가 가지고 있는 테이블 다 지우고 다시 생성
    properties :
      hibernate :
        # showsql : true
        format_sql : true

logging :
  level :
    org.hibernate.SQL : debug